project_name: ncci
before:
  hooks:
  - go get ./...
builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
brews:
  -
    tap:
      owner: bigbinary
      name: homebrew-tap
    folder: Formula
    homepage:  https://neetoci.com
    description: neetoCI 1.0 command line interface.
    test: |
      system "#{bin}/ncci version"
